Repository noncelab/bitcoin-haerye, pull requests merged in 2023-04, with the labels that each got.

#1 mastering bitcoin chap 5
  mastering bitcoin/ch05.md
  mastering bitcoin/index.md
Labels: new content

#4 이미지 크기 조정 및 포맷 수정
  mastering bitcoin/ch05.md
Labels: layout issue

#5 BIP-39
  bip/bip-0032.md
  bip/bip-0039.md
Labels: new content

#8 BIP-39 팁이 있는 글자 기울임 처리
  bip/bip-0039.md
Labels: layout issue

#16 예시 문서 포맷 추가
  .gitignore
  bip/bip-0039.md
  guidelines/contributing.md
  guidelines/format/bip.md
  guidelines/format/etc.md
  guidelines/format/mastering-bitcoin.md
  mastering bitcoin/ch05.md
Labels: suggestion
